/* Observation-only presentation. No model calculations or mutation requests. */
(() => {
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=v=>typeof v==='number'&&Number.isFinite(v), num=v=>finite(v)?v.toFixed(3):'Not observed';
const key=(...v)=>JSON.stringify(v), missing='Not recorded';
let live={scope:document.getElementById('territories')?'agent':'namespace',agent:null,nodes:[],edges:[],events:[]}, view='overview', ns=null, context=undefined, relation=null, selected=null, eventId=null, page=0;
let healthLabel='Server status ↗',healthChecked='Not checked';
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const labels=new Map();
const root=document.createElement('section');root.id='researchDashboard';root.setAttribute('aria-label','Ember research observation dashboard');
root.innerHTML='<div class="rd-head" id="rdHead"></div><nav id="rdNav" aria-label="Research views"></nav><main class="rd-main" id="rdMain"></main><aside class="rd-panel rd-inspector" id="rdInspector" aria-label="Selected memory and event inspector"></aside><section class="rd-panel rd-timeline" id="rdTimeline" aria-label="Activity timeline"></section>';
document.querySelector('header').after(root);document.body.classList.add('rd-active');
const $=id=>document.getElementById(id), data=()=>live;
function label(id,namespace=ns){const k=key(namespace,id);if(!labels.has(k))labels.set(k,labels.size+1);const n=data().nodes.find(x=>x.id===id&&x.namespace===namespace);return `Memory ${String(labels.get(k)).padStart(3,'0')} — ${(n?.subject||n?.title||'Untitled memory').slice(0,36)}`}
function normalize(e,namespace){const o=e.observation||e;return {...e,namespace:e.namespace||namespace,event_id:e.event_id||e.id,context:o.context,event_type:o.operation||e.event_type||e.report?.feedback_type||e.action,observed_agent_id:e.observed_agent_id||e.actor,session:e.session||o.session_ref||null,query:o.query,direct_ids:o.direct_ids||[],returned_ids:o.returned_ids||[],pair_expansion:o.pair_expansion||null,memory_ids:o.memory_ids||e.memory_ids||[],changes:e.changes||e.transitions||[],report:e.feedback||e.report||null,actual_H:o.observed_heat||e.actual_H||{}}}
function title(e){const p=e.pair_expansion,t=e.report?.target;const id=e.memory_ids?.[0]||e.returned_ids?.[0];if(p)return `Pairing added one related memory: ${label(p.target,e.namespace)}`;if(e.event_type?.startsWith('memory_written'))return `${id?label(id,e.namespace):'A memory'} was created`;if(e.event_type==='PAIR_HELPED')return t?`${label(t.memory_ids[0],e.namespace)} → ${label(t.memory_ids[1],e.namespace)} was marked helpful`:'A directional pair was marked helpful';if(e.event_type==='UNUSED')return 'Memory appeared but was not used';if(e.event_type?.includes('recall'))return `${id?label(id,e.namespace):'Memories'} recalled`;return ({CONTRIBUTED:'A memory helped in this context',IRRELEVANT:'A memory was reported irrelevant',PAIR_IRRELEVANT:'A pair route was reported irrelevant',resolve:'An evidence decision was recorded',merge:'Experiences were merged',split:'An experience was split'})[e.event_type]||e.event_type||'Recorded event'}
function scopeRows(){const d=data();let namespaces=[...new Set(d.nodes.map(n=>n.namespace).concat(d.events.map(e=>e.namespace)))].filter(x=>x!=null);if(!namespaces.includes(ns))ns=namespaces[0]??null;const nodes=d.nodes.filter(n=>n.namespace===ns);const edges=d.edges.filter(e=>e.namespace===ns);const contexts=[...new Map(edges.filter(e=>e.kind==='pair_evidence').map(e=>[key(e.context),e.context]).concat(nodes.flatMap(n=>(Array.isArray(n.usefulness)?n.usefulness:[]).map(u=>[key(u.context),u.context])))).values()];if(context===undefined||!contexts.some(c=>key(c)===key(context)))context=contexts[0];const types=[...new Set(edges.filter(e=>e.kind==='pair_evidence'&&key(e.context)===key(context)).map(e=>e.type))];if(!types.includes(relation))relation=types[0]||null;return {d,namespaces,nodes,edges,contexts,types}}
// Reconcile existing elements on delivery; do not replace the graph on each event.
function patch(container,markup){const template=document.createElement('template');template.innerHTML=markup;const identity=n=>n.nodeType===1?(n.id||n.getAttribute('data-node')||n.getAttribute('data-event')||n.getAttribute('data-pair')):null;
function sync(parent,wanted){const existing=[...parent.childNodes];const keyed=new Map(existing.filter(identity).map(n=>[identity(n),n]));let cursor=parent.firstChild;for(const want of [...wanted.childNodes]){const id=identity(want);let got=id?keyed.get(id):cursor;if(!got||got.nodeType!==want.nodeType||got.nodeName!==want.nodeName||(identity(got)&&identity(got)!==id)){got=want.cloneNode(true);parent.insertBefore(got,cursor)}else{if(got!==cursor)parent.insertBefore(got,cursor);if(got.nodeType===3){if(got.textContent!==want.textContent)got.textContent=want.textContent}else if(got.nodeType===1){for(const a of [...got.attributes])if(!want.hasAttribute(a.name))got.removeAttribute(a.name);for(const a of [...want.attributes])if(got.getAttribute(a.name)!==a.value)got.setAttribute(a.name,a.value);sync(got,want)}}cursor=got.nextSibling}while(cursor){const next=cursor.nextSibling;cursor.remove();cursor=next}}
sync(container,template.content)}
function render(){const s=scopeRows();const scope=s.d.scope==='agent'?'Agent-observer-scoped':'Namespace-scoped';$('rdHead').innerHTML=`<span><strong>${scope}</strong><br><small>${esc(s.d.agent||'Agent not observed')}</small></span><span>${s.nodes.length} visible memories<br><small>${s.edges.length} recorded relationships · bounded view</small></span><select id="rdNamespace" aria-label="Visible namespace">${s.namespaces.map(n=>`<option ${n===ns?'selected':''}>${esc(n)}</option>`).join('')||'<option>No namespace observed</option>'}</select><div class="rd-tools"><button data-action="diagnostics">Transport</button><button data-action="help" title="Explain the memory system">? Help</button><button data-action="status" title="${esc(healthChecked)}">${esc(healthLabel)}</button></div>`;
$('rdNamespace').onchange=e=>{ns=e.target.value;selected=null;context=undefined;page=0;render()};
$('rdNav').innerHTML=[['overview','Overview'],['graph','Relationship Graph'],['matrix','Pairing Matrix'],['flow','Memory Flow'],['activity','Activity'],['spatial','Spatial views'],['simulation','Simulation'],['help','Help & glossary']].map(([k,v])=>`<button data-view="${k}" class="${view===k?'active':''}">${v}</button>`).join('')+'<div class="rd-guidance">Useful does not mean true.<br>A relationship does not prove causation.<br>Pairing is context-specific.<br><br>Memory groups organize the view by subject/context; they do not merge namespaces.</div>';
const main=$('rdMain');let markup='';document.body.classList.toggle('rd-spatial',view==='spatial');document.body.classList.toggle('rd-active',view!=='spatial');
if(view==='spatial'){markup='';}
else if(view==='overview'){markup=graph(s)+matrix(s);}
else if(view==='graph')markup=graph(s);
else if(view==='matrix')markup=matrix(s,false);
else if(view==='flow')markup=flow(s);
else if(view==='activity')markup=`<section class="rd-panel">${timeline(s.d.events,true)}</section>`;
else if(view==='help')markup=help();
else if(view==='simulation')markup=`<div class="rd-sim">Live memory motion · actual observed data · movement is visual layout, not H or learning. <button data-action="motion">${motion?'Pause motion':'Resume motion'}</button></div>${graph(s)}`;
patch(main,markup);patch($('rdTimeline'),timeline(s.d.events.slice(-30)));
renderInspector(s);bind();}
function graph(s){const nodes=s.nodes.slice(page*24,page*24+24), ids=new Set(nodes.map(n=>n.id)), edges=s.edges.filter(e=>ids.has(e.from)&&ids.has(e.to)&&(e.kind!=='pair_evidence'||key(e.context)===key(context))).slice(0,80);const W=900,H=nodes.length<=10?360:Math.max(360,Math.ceil(nodes.length/4)*100);const center=nodes.findIndex(n=>n.id===selected);const order=center>0?[nodes[center],...nodes.filter((n,i)=>i!==center)]:nodes;const pos=new Map(order.map((n,i)=>[n.id,nodes.length<=10?(i===0?{x:450,y:180}:{x:450+325*Math.cos((i-1)*Math.PI*2/Math.max(1,nodes.length-1)-Math.PI/2),y:180+135*Math.sin((i-1)*Math.PI*2/Math.max(1,nodes.length-1)-Math.PI/2)}):{x:115+(i%4)*220,y:55+Math.floor(i/4)*100}]));let svg='';for(const [i,e]of edges.entries()){const a=pos.get(e.from),b=pos.get(e.to),highlight=!selected||[e.from,e.to].includes(selected),kind=e.kind==='pair_evidence'?'pair':e.kind==='recorded_provenance'?'provenance':'';const dx=b.x-a.x,dy=b.y-a.y,scale=Math.max(Math.abs(dx)/80,Math.abs(dy)/29,1),ax=a.x+dx/scale,ay=a.y+dy/scale,bx=b.x-dx/scale,by=b.y-dy/scale,cy=(ay+by)/2-8;svg+=`<g opacity="${highlight?1:.15}"><path data-from="${esc(e.from)}" data-to="${esc(e.to)}" class="rd-edge ${kind}" d="M ${ax} ${ay} Q ${(ax+bx)/2} ${cy} ${bx} ${by}" marker-end="url(#rdArrow)"/><text opacity="${edges.length<=18||(selected&&[e.from,e.to].includes(selected)&&i<24)?1:0}" class="rd-edge-label" x="${(ax+bx)/2}" y="${cy-7}" text-anchor="middle">${esc(e.type)}${finite(e.W)?' · '+num(e.W):''}</text><title>${esc(e.kind)}: ${esc(label(e.from))} → ${esc(label(e.to))}; context ${esc(e.context??'not recorded / unset')}</title></g>`}
for(const n of nodes){const p=pos.get(n.id);svg+=`<g class="rd-node ${selected===n.id?'selected':''}" data-node="${esc(n.id)}" tabindex="0" role="button" aria-label="${esc(label(n.id))}" transform="translate(${p.x},${p.y})"><rect x="-76" y="-24" width="152" height="49" rx="8"/><text x="0" y="-5" text-anchor="middle">${esc(label(n.id).split(' — ')[0])}</text><text x="0" y="12" text-anchor="middle">${esc((n.subject||'Untitled memory').slice(0,23))}</text><title>${esc(label(n.id))}\n${esc(n.id)}</title></g>`}
return `<section class="rd-panel rd-graph"><div class="rd-bar"><h2>Memory Relationship Graph</h2><small>${esc(ns||'No namespace')} · layout has no model meaning</small>${pager(s.nodes.length,24)}</div>${nodes.length?`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Directional recorded memory relationships"><defs><marker id="rdArrow" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6" fill="currentColor"/></marker></defs>${svg}</svg>`:'<div class="rd-empty">No memories observed yet. Open an authorized viewing link.</div>'}<div class="rd-legend">Solid → stored relationship · Dashed → contextual pair evidence · Dotted → source/provenance<br>${!edges.length?'No relationships recorded among these visible memories. ':''}Select a memory to highlight incoming/outgoing connections. Maximum 24 nodes / 80 edges per page.</div></section>`}
function pager(total,size){return total>size?`<button data-action="prev" aria-label="Previous memory page">←</button><small>Page ${page+1} / ${Math.ceil(total/size)}</small><button data-action="next" data-max="${Math.ceil(total/size)-1}" aria-label="Next memory page">→</button>`:''}
function matrix(s,compact=true){const nodes=s.nodes.slice(page*12,page*12+12);const weights=s.edges.filter(e=>e.kind==='pair_evidence'&&key(e.context)===key(context)&&e.type===relation);const cell=(a,b)=>weights.find(e=>e.from===a.id&&e.to===b.id);return `<section class="rd-panel ${compact?'rd-matrix':''}"><div class="rd-bar"><h2>Pairing Matrix →</h2><select id="rdContext" aria-label="Pairing context">${s.contexts.map(c=>`<option value="${esc(JSON.stringify(c))}" ${key(c)===key(context)?'selected':''}>${esc(c===null?'Explicitly unset context':c)}</option>`).join('')||'<option>No context observed</option>'}</select><select id="rdRelation" aria-label="Pair relationship type">${s.types.map(t=>`<option ${t===relation?'selected':''}>${esc(t)}</option>`).join('')||'<option>No pair type observed</option>'}</select>${pager(s.nodes.length,12)}<small>Weaker 0 ─── 1 Stronger · — not observed</small></div><div style="overflow:auto"><table aria-label="Directional contextual pair weights"><thead><tr><th>From ↓ / To →</th>${nodes.map(n=>`<th title="${esc(label(n.id))}">${esc(label(n.id).split(' — ')[0])}</th>`).join('')}</tr></thead><tbody>${nodes.map(a=>`<tr><th>${esc(label(a.id))}</th>${nodes.map(b=>{const w=cell(a,b);return `<td class="${finite(w?.W)?'':'rd-missing'}" ${finite(w?.W)?`style="background:color-mix(in srgb,var(--rd-accent) ${Math.round(w.W*45)}%,var(--rd-panel))"`:''}><button data-pair="${esc(key(a.id,b.id))}" title="${esc(label(a.id)+' → '+label(b.id)+'; '+(relation||missing)+'; '+(context??'unset'))}">${finite(w?.W)?num(w.W):'—'}</button></td>`}).join('')}</tr>`).join('')}</tbody></table></div><p class="rd-legend">Pairing Matrix shows which related memories have historically been useful when reached from another memory in this context. It is directional and context-specific. It does not mean truth or causation. Each cell is one relation type; no averaged W.</p></section>`}
function timeline(events,full=false){return `<div class="rd-bar"><h2>Activity / recorded events</h2><small>${events.length} visible · click to explain</small></div>${events.slice().reverse().map(e=>`<button class="rd-event" data-event="${esc(key(e.namespace,e.event_id))}">${esc(title(e))}<small>${esc(e.observed_agent_id||'Agent not recorded')} · ${esc(e.namespace)} · context ${esc(e.context??'unset / not recorded')} · session ${esc(e.session||'Not recorded')} · ${esc(e.event_type)} · revision ${esc(e.revision??missing)}</small></button>`).join('')||'<p class="rd-empty">No activity observed. Viewing does not invoke retrieval.</p>'}`}
const stageNames=['Agent task/query','Context','Direct retrieval','Primary memory selected','Pairing Matrix check','Returned memories','Agent use / ignore','Feedback','U / W updates','Truth remains separate'];
function stageData(e){if(!e)return Array(10).fill(null);return [e.query?{query:e.query,agent:e.observed_agent_id}:null,e.context!==undefined?{context:e.context}:null,e.direct_ids.length?{memory_ids:e.direct_ids}:null,e.direct_ids.length?{primary_memory:e.direct_ids[0]}:null,e.pair_expansion||null,e.returned_ids.length?{memory_ids:e.returned_ids}:null,e.report?{reported_feedback:e.report.feedback_type,note:e.report.note??missing}:null,e.report||((e.action==='resolve')?{action:e.action,experiences:e.experiences}:null),e.changes.length?e.changes:null,e.truth_before!==undefined?{before:e.truth_before,after:e.truth_after}:null]}
function flow(s){const e=s.d.events.find(e=>key(e.namespace,e.event_id)===eventId)||s.d.events.filter(e=>e.namespace===ns).at(-1),values=stageData(e);return `<section class="rd-panel"><div class="rd-bar"><h2>Memory Flow</h2><small>${esc(e?title(e):'Select a recorded event')}</small></div><p class="rd-legend">One event at a time. Missing stages are not inferred or joined by proximity. Select a timeline event to inspect another step.</p><div class="rd-flow">${stageNames.map((name,i)=>`<button class="rd-step" data-stage="${i}" data-flow-event="${esc(e?key(e.namespace,e.event_id):'')}">${i+1}. ${name}<small>${values[i]?'Recorded — inspect details':'Not observed'}</small></button>`).join('')}</div></section>`}
function stageExplanation(e,i){const p=e.pair_expansion||{},ids=a=>(a||[]).map(id=>label(id,e.namespace)).join('; ');const rows=[
{entered:e.query,happened:'An agent query was recorded.',out:'Not observed'},
{entered:e.context===null?'Explicitly unset context':e.context,happened:'This event carries the recorded working context.',out:e.context===null?'Explicitly unset context':e.context},
{entered:'Direct candidate scores are not exposed here.',happened:'These direct memories were admitted by normal retrieval.',out:ids(e.direct_ids)},
{entered:ids(e.direct_ids),happened:'The first admitted direct memory is the primary memory.',out:ids(e.direct_ids.slice(0,1))},
{entered:ids([p.source]),happened:`A paired route was recorded: ${p.relation||missing}, W ${num(p.W)}.`,out:ids([p.target])},
{entered:'See direct and paired stages where recorded.',happened:'These memory IDs were returned.',out:ids(e.returned_ids)},
{entered:e.report?.feedback_type,happened:'Agent use or non-use was explicitly reported; internal thinking is not observed.',out:e.report?.feedback_type},
{entered:e.report?.feedback_type||e.action,happened:'An explicit feedback or evidence decision was recorded.',out:'See recorded feedback fields.'},
{entered:'Recorded before-state in the transition details.',happened:'The event contains explicit state transitions.',out:'Recorded after-state in the transition details.'},
{entered:e.truth_before,happened:'Only explicitly recorded truth evidence is shown.',out:e.truth_after}];return rows[i]}
function field(k,v){return `<dt>${esc(k)}</dt><dd>${esc(v??missing)}</dd>`}
function renderInspector(s){const n=s.nodes.find(n=>n.id===selected);if(!n){$('rdInspector').innerHTML='<h2>Memory Inspector</h2><p class="rd-muted">Select a memory, matrix cell or flow stage.</p><p>Useful does not mean true.</p>';return}const u=Array.isArray(n.usefulness)?n.usefulness.find(x=>key(x.context)===key(context)):n.usefulness;const p=n.provenance||{},edges=s.edges.filter(e=>[e.from,e.to].includes(n.id));$('rdInspector').innerHTML=`<h2>${esc(label(n.id))}</h2><p class="rd-muted">${esc(n.id.slice(0,8))}</p><p>${esc(n.preview||n.data?.content||'Content not recorded')}</p><dl>${field('Subject',n.subject)}${field('Primary context',n.primary_context===null?'Explicitly unset':n.primary_context)}${field('Full memory ID',n.id)}${field('Originating agent',p.originating_agent||p.creator_agent)}${field('Creation event',p.creation_event)}${field('Source memories',p.source_ids?.length?p.source_ids.join(', '):missing)}${field('Consolidation history',p.consolidated?'Recorded consolidation':missing)}</dl>${metric('Helpful in this context','Usefulness (U)',u?.value)}${metric('Evidence supporting this','Evidence mass (N_eff)',u?.N_eff)}${metric('Current activation','Activation Heat (H)',n.heat??n.actual_H?.value)}<small>Measurement context: ${esc(u?.context??'Not recorded / unset')}. H is never inferred from U. Activation context: ${esc(n.actual_H?.context??n.dynamics?.context??'Not recorded')}.</small><dl>${field('Truth status',n.truth_status||n.verify_status)}</dl><h3>How this memory points to others · W</h3>${edges.map(e=>`<p>${e.from===n.id?'Outgoing →':'Incoming ←'} ${esc(label(e.from===n.id?e.to:e.from))}<br><small>${esc(e.type)} · ${esc(e.kind)} · W ${num(e.W)} · context ${esc(e.context??'Not recorded / unset')}</small></p>`).join('')||'<p>Relationships not recorded.</p>'}<h3>Recent changes</h3>${s.d.events.filter(e=>e.memory_ids.includes(n.id)||e.returned_ids.includes(n.id)||e.changes.some(c=>c.after?.target?.memory_ids?.includes(n.id))).slice(-5).map(e=>`<p>${esc(title(e))} · r${esc(e.revision)}</p>`).join('')||'Not observed'}`}
function metric(plain,technical,value){return `<div class="rd-metric"><span>${plain}<br><small>${technical}</small></span><b>${num(value)}</b></div>`}
const glossary={Memory:'A stored record. Its content and truth status are separate from whether it helped.',Context:'The exact working context supplied by an agent. Similar wording does not mean identical context.','Usefulness U':'Recorded contextual helpfulness for one memory. Useful does not mean true.','Pair Weight W':'Recorded helpfulness of a specific source → target route, relationship type and context. It does not influence direct LADC admission.','Activation H':'Actual recorded activation. Missing H is not zero, and is never estimated from usefulness.','Evidence mass N_eff':'Effective evidence mass after the existing feedback rules handle duplicates and corrections. It is not the number of views.','Pairing Matrix':'Directional, contextual pair-usefulness values. V1 may add at most one eligible related memory after direct selection, within existing capacity.','Memory Flow':'An explanation of observed stages, not an inferred trace of the agent’s thoughts.','Namespace scope':'Only the authorized memory namespace. Graph edges never join namespaces in this view.','Research observer scope':'Follows the authorized agent across permitted namespaces and sessions. Visibility is aggregated; memory spaces remain separate.','Graph layout':'Position and movement organize the screen. A relationship does not prove causation.'};
function help(){return '<section class="rd-panel rd-help"><h2>Understanding Ember</h2>'+Object.entries(glossary).map(([k,v])=>`<h3>${esc(k)} <span title="${esc(v)}">?</span></h3><p>${esc(v)}</p>`).join('')+'</section>'}
function bind(){root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;page=0;render()});root.querySelectorAll('[data-node]').forEach(b=>{b.onclick=()=>{selected=b.dataset.node;render()};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click()}}});root.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{eventId=b.dataset.event;view='flow';render()});root.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{const [a,z]=JSON.parse(b.dataset.pair),e=scopeRows().edges.find(e=>e.from===a&&e.to===z&&e.kind==='pair_evidence'&&e.type===relation&&key(e.context)===key(context));$('rdInspector').innerHTML=`<h2>${esc(label(a))} → ${esc(label(z))}</h2><p>${esc(relation||missing)} · context ${esc(context??'unset / not recorded')}</p>${metric('How strongly this memory points to another','Pair weight (W)',e?.W)}${metric('Evidence supporting this route','Evidence mass (N_eff)',e?.N_eff)}<p>${e?'Recorded pair state. This is not a truth score or proof of causation.':'Not observed. An empty cell does not mean W = 0.'}</p>`});root.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{const e=data().events.find(e=>key(e.namespace,e.event_id)===b.dataset.flowEvent),i=Number(b.dataset.stage),v=stageData(e)[i];$('rdInspector').innerHTML=`<h2>${stageNames[i]}</h2><dl>${field('What entered',v?stageExplanation(e,i).entered:'Not observed')}${field('What happened',v?stageExplanation(e,i).happened:'Not observed')}${field('What came out',v?stageExplanation(e,i).out:'Not observed')}${field('What changed',i===8&&v?'Recorded before/after state below':'Not observed in this stage')}${field('What did not change',i===9&&v&&key(v.before)===key(v.after)?'Recorded truth state unchanged':'Not observed')}</dl><pre>${esc(v?JSON.stringify(v,null,2):'Not observed')}</pre><p>Opening this explanation changes no memory or learning state.</p>`});$('rdContext')?.addEventListener('change',e=>{context=JSON.parse(e.target.value);render()});$('rdRelation')?.addEventListener('change',e=>{relation=e.target.value;render()});root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{switch(b.dataset.action){case 'diagnostics':{const d=window.emberObserverTransport||window.emberTransport||{};$('rdInspector').innerHTML='<h2>Transport diagnostics</h2><dl>'+['connection_state','transport','stream_id','last_received_event_id','reconnect_count','snapshot_gets','snapshot_get_count','fallback_count','last_disconnect_reason','last_http_status','grant_expires_at'].map(k=>field(k.replaceAll('_',' '),d[k])).join('')+'</dl><p>API availability is separate from SSE status. Missing counters are not assumed zero.</p>';return;}case 'help':view='help';break;case 'status':window.open('/status','_blank','noopener');return;case 'prev':page=Math.max(0,page-1);break;case 'next':page=Math.min(Number(b.dataset.max),page+1);break;case 'motion':motion=!motion;break;}render()})}
window.EmberResearchUI={namespace(d){live={scope:'namespace',agent:(d.events||[]).at(-1)?.actor||null,nodes:(d.nodes||[]).map(n=>({...n,namespace:d.namespace})),edges:(d.edges||[]).map(e=>({...e,namespace:d.namespace})),events:(d.events||[]).map(e=>normalize(e,d.namespace))};render()},observer(e){live.scope='agent';live.agent=e.observed_agent_id;const nmap=new Map(live.nodes.map(n=>[key(n.namespace,n.id),n]));for(const m of e.memories||[])nmap.set(key(e.namespace,m.id),{...nmap.get(key(e.namespace,m.id)),...m,namespace:e.namespace});live.nodes=[...nmap.values()].slice(-500);const emap=new Map(live.edges.map(r=>[key(r.namespace,r.from,r.to,r.type,r.kind,r.context),r]));for(const r of e.relationships||[])emap.set(key(e.namespace,r.from,r.to,r.type,r.kind,r.context),{...r,namespace:e.namespace});for(const delta of e.changes||[]){const s=delta.after;if(!s)continue;const ids=s.target?.memory_ids||[];if(s.metric==='W'){const r={namespace:e.namespace,from:ids[0],to:ids[1],type:s.target.relation,kind:'pair_evidence',context:s.context,W:s.value,N_eff:s.N_eff};emap.set(key(r.namespace,r.from,r.to,r.type,r.kind,r.context),r)}if(s.metric==='U'){const n=nmap.get(key(e.namespace,ids[0]));if(n){const u=Array.isArray(n.usefulness)?n.usefulness:[];n.usefulness=[...u.filter(x=>key(x.context)!==key(s.context)),s]}}}for(const [id,h]of Object.entries(e.actual_H||{})){const n=nmap.get(key(e.namespace,id));if(n)n.actual_H={value:h,context:e.context}}live.edges=[...emap.values()].slice(-1000);const event=normalize(e);live.events=[...live.events.filter(x=>key(x.namespace,x.event_id)!==key(e.namespace,e.event_id)),event].slice(-200);{ns=e.namespace;render();$('rdTimeline').firstElementChild?.nextElementSibling?.classList.add('rd-pulse')}},clear(){live={scope:live.scope,agent:null,nodes:[],edges:[],events:[]};labels.clear();selected=null;ns=null;render()},getState(){return structuredClone(data())}};
let lastFrame=0;
function animate(time){if(view==='simulation'&&motion&&time-lastFrame>50){lastFrame=time;const points=new Map();root.querySelectorAll('.rd-node').forEach((g,i)=>{if(!g.dataset.base)g.dataset.base=g.getAttribute('transform');const xy=g.dataset.base.match(/[-\d.]+/g).map(Number);const x=xy[0]+Math.sin(time/2400+i)*8,y=xy[1]+Math.cos(time/2700+i)*7;points.set(g.dataset.node,{x,y});g.setAttribute('transform',`translate(${x},${y})`)});root.querySelectorAll('.rd-edge').forEach(p=>{const a=points.get(p.dataset.from),b=points.get(p.dataset.to);if(!a||!b)return;const dx=b.x-a.x,dy=b.y-a.y,scale=Math.max(Math.abs(dx)/80,Math.abs(dy)/29,1);p.setAttribute('d',`M${a.x+dx/scale},${a.y+dy/scale} Q${(a.x+b.x)/2},${(a.y+b.y)/2-10} ${b.x-dx/scale},${b.y-dy/scale}`);const t=p.parentNode.querySelector('text');if(t){t.setAttribute('x',(a.x+b.x)/2);t.setAttribute('y',(a.y+b.y)/2-14)}})}requestAnimationFrame(animate)}
fetch('/health',{cache:'no-store'}).then(async r=>{const d=await r.json();healthLabel=r.ok&&d.status==='ok'?'API responding ↗':'API response error ↗';healthChecked='Availability checked '+new Date().toLocaleTimeString()+'; SSE status is separate';render()}).catch(()=>{healthLabel='API unavailable ↗';healthChecked='Health request failed; open details';render()});
requestAnimationFrame(animate);render();
})();
