/* Public read-only availability probes only. Never opens streams or reads memory. */
(() => {
'use strict';
const endpoints=[['API','/health'],['Observer build','/v1/observer/build'],['Observer page','/observer'],['Namespace page','/visualizer'],['Research settings page','/research/settings'],['Status page','/status'],['Transport asset','/v1/observer/transport.js']];
const full=!!document.getElementById('endpointStatus'),targets=full?endpoints:endpoints.slice(0,1);
const style=document.createElement('style');style.textContent='.ember-health{display:inline-flex;align-items:center;gap:8px;font:12px system-ui;color:inherit;text-decoration:none}.health-dot{width:10px;height:10px;border-radius:50%;background:#929a9e;flex-shrink:0}.ember-health[data-health=green] .health-dot{background:#50b985}.ember-health[data-health=yellow] .health-dot{background:#d6b653}.ember-health[data-health=red] .health-dot{background:#e87878}.health-row{display:grid;grid-template-columns:minmax(130px,1fr) 1fr;gap:10px;padding:14px 0;border-bottom:1px solid var(--line,#383b3e)}.health-row small{grid-column:1/-1;overflow-wrap:anywhere}';document.head.append(style);
const badge=document.createElement('a');badge.href='/status';badge.className='ember-health';badge.dataset.health='unknown';badge.setAttribute('aria-live','polite');badge.innerHTML='<span class="health-dot" aria-hidden="true"></span><span>API · checking</span>';document.querySelector('header').append(badge);
const rows=new Map();for(const [name,url]of targets){rows.set(url,{name,url,color:'unknown',label:'Checking',detail:'No observation yet',at:null});}
let timer=null,running=false,stopped=false;const controllers=new Set();
function paint(){const all=[...rows.values()],api=rows.get('/health');badge.dataset.health=api.color;badge.lastElementChild.textContent='API · '+api.label;badge.title=api.detail+' · API availability only; not model health or SSE status';
if(!full)return;const host=document.getElementById('endpointStatus');host.replaceChildren();for(const row of all){const box=document.createElement('div');box.className='health-row';const name=document.createElement('b');name.textContent=row.name;const state=document.createElement('span');state.className='ember-health';state.dataset.health=row.color;const dot=document.createElement('span');dot.className='health-dot';dot.setAttribute('aria-hidden','true');state.append(dot,document.createTextNode(row.label));const detail=document.createElement('small');detail.textContent=row.url+' · '+row.detail+(row.at?' · '+new Date(row.at).toLocaleTimeString():'');box.append(name,state,detail);host.append(box)}
document.getElementById('checked').textContent='Automatic checks every 15 seconds while visible. Slow ≥ 2 seconds; timeout 8 seconds. Last cycle '+new Date().toLocaleTimeString();}
async function probe(row){const controller=new AbortController();controllers.add(controller);const timeout=setTimeout(()=>controller.abort(),8000),start=performance.now();try{const response=await fetch(row.url,{cache:'no-store',credentials:'omit',redirect:'error',signal:controller.signal});let health=null;if(row.url==='/health'&&response.ok)health=await response.json();else await response.arrayBuffer();if(stopped)return;const ms=Math.round(performance.now()-start);row.color=response.status>=500?'red':!response.ok?'yellow':health&&health.status!=='ok'?'yellow':ms>=2000?'yellow':'green';row.label=row.color==='green'?'Healthy':row.color==='red'?'Unavailable':!response.ok?'Blocked / partial':ms>=2000?'Slow':'Degraded';row.detail='HTTP '+response.status+' · '+ms+' ms';}catch(error){if(stopped)return;row.color='red';row.label='Unavailable';row.detail=controller.signal.aborted?'Timed out after 8 seconds':'Request failed from this browser';}finally{clearTimeout(timeout);controllers.delete(controller);row.at=Date.now();if(!stopped)paint();}}
async function cycle(){if(stopped||running||document.hidden)return;running=true;try{await Promise.all([...rows.values()].map(probe));}finally{running=false;if(!stopped)timer=setTimeout(cycle,15000);}}
document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)cycle()});window.addEventListener('pagehide',()=>{stopped=true;clearTimeout(timer);for(const c of controllers)c.abort()});window.addEventListener('pageshow',e=>{if(e.persisted){stopped=false;cycle()}});
// SSE state is independently sourced from the existing connection badge.
const connection=document.getElementById('status')||document.getElementById('connection');if(connection){const stream=document.createElement('span');stream.className='ember-health';stream.setAttribute('aria-live','polite');document.querySelector('header').append(stream);const update=()=>{const state=connection.textContent.trim();stream.dataset.health=state==='LIVE'?'green':/EXPIRED|ERROR|FAILED|DENIED/.test(state)?'red':'yellow';stream.replaceChildren();const dot=document.createElement('span');dot.className='health-dot';dot.setAttribute('aria-hidden','true');stream.append(dot,document.createTextNode('Stream · '+state));stream.title='Observed SSE transport state only';};new MutationObserver(update).observe(connection,{childList:true,characterData:true,subtree:true});update();}
paint();cycle();
})();
